### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by ReesesSnickers** [ReesesSnickers/BlogAsAPortfolio#29]
Need to come up with a logo\branding

**Comment by ReesesSnickers** [comment]
@richardbmx I really appreciate the offer to do this. I was actually just thinking about this today on what I was going to do regarding a logo for the project. I was working to do this so I would have a website to host my portfolio and resume on. If you have time I would love to see your work. I hope your day goes well!

**Comment by richardbmx** [comment]
[https://richardbmx.github.io/](Here) you can see my work portfolio. I will work on some ideas to develop your logo and when you have some samples I will show them to you

**Comment by ReesesSnickers** [comment]
@richardbmx I really appreciate your help. Never ventured on the graphics design side of development yet. Can't wait to see what you come up with.

**Comment by richardbmx** [comment]
I present this proposal that is based on representing a book or notebook to give blog personality as you can see it adapts very well in different color formats

![logo120](https://user-images.githubusercontent.com/35604837/48747795-05def400-ec4b-11e8-99a3-74d581a67cce.png)

**Comment by ReesesSnickers** [comment]
I definitely love the notebook. especially the first one. Personally like "BLOGASAPORTFOLIO" more though. Is that easily changed?

**Comment by ReesesSnickers** [comment]
Also, is this a free contribution?

**Comment by richardbmx** [comment]
If it can be changed without problem. I show you two variations by placing the word ASA in color to differentiate in the text and I have placed it in two lines so that the text is not too long

![logo1202](https://user-images.githubusercontent.com/35604837/48748880-ca462900-ec4e-11e8-8f76-7c12477314d8.png)

**Comment by richardbmx** [comment]
If the contribution is free I do it to extend my portfolio

**Comment by ReesesSnickers** [comment]
I really do appreciate this. If it's possible to get both a one just the notebook as well as one with the name id be appreciative. I'll be sure to follow you and do what I can to help promote your portfolio and work.

**Comment by richardbmx** [comment]
Perfect I will create a google folder with all the necessary files to use it, so if you want you can perform a pull requests adding the logo to the readme file and the project

**Comment by ReesesSnickers** [comment]
Can do. when you have the folder set up, just let me know

**Comment by richardbmx** [comment]
@ReesesSnickers  Here you can find a Google folder with all the necessary files to use the logo, find different variations in different formats and also open a file that grants all the rights for free use.

[Google Dirve](https://drive.google.com/open?id=10qE-8FK9NMYZSt1Q454cTw0LjpzfpF6y)

**Comment by ReesesSnickers** [comment]
@richardbmx I really do appreciate you taking the time to do the logo for me. I will work on getting a readme set up soon.

**Comment by richardbmx** [comment]
do not worry I hope you liked i...t If you want some design in future projects you can communicate with me
